#!/bin/bash

git add .

read -p "Type (feat, fix, docs, style, refactor, perf, test, chore): " TYPE
read -p "Scope (describe parts of the code affected): " SCOPE
read -p "Subject (description of the applied changes): " SUBJECT
read -p "Body (additional contextual information about the change): " BODY
read -p "Footer (reference affected code changes): " FOOTER

git commit -m "$TYPE($SCOPE): ($SUBJECT)\n\n$BODY\n$FOOTER"

git push
